### ISSUE TITLE
WorkerError econnrefused

### ISSUE THREAD

**Issue by superhuy** [andersju/webbkoll#2]
Hello,
i'm trying to setup Webbkoll but i get this error.

[error] Process #PID<0.488.0> raised an exception
** (WorkerError) econnrefused
    (webbkoll) lib/webbkoll/worker.ex:71: Webbkoll.Worker.handle_error/2
    (webbkoll) lib/webbkoll/worker.ex:20: Webbkoll.Worker.perform/4
    (exq) lib/exq/worker/server.ex:119: anonymous fn/3 in Exq.Worker.Server.dispatch_work/2

Can anybody help me, please?

**Comment by andersju** [comment]
Hi! It sounds like you don't have PhearJS running. See https://github.com/Tomtomgo/phearjs/blob/master/README.md. Also make sure it's running on the port specified in Webbkoll's `config/dev.exs` (or `config/prod.exs` if you're running in production mode).

**Comment by superhuy** [comment]
Thank you for you quick response.
It works!
