### ISSUE TITLE
GeoIP path change

### ISSUE THREAD

**Issue by arlogilbert** [andersju/webbkoll#21]
It looks like the maxmind databases have moved to a slightly different URL which is easy to change in the config, but now instead of being a pure .gz file it is a .tar.gz file and the code does not know what to do with the tar file.

I've tried installing a mix tar package but I'm pretty new to mix and unclear what I"m doing wrong. Any suggestions?

**Comment by andersju** [comment]
Thanks for the heads up! Looks like the old URLs still work, but I might as well change them now. The fix I just committed should work. Turns out Erlang already comes with a [tar module](http://erlang.org/doc/man/erl_tar.html) so no extra dependency necessary :)
