### ISSUE TITLE
Commented img Tag still showing up as 3rd Party request

### ISSUE THREAD

**Issue by NiklasDah** [andersju/webbkoll#24]
### Description
When commenting out an img tag (e.g.: `<!-- img src="https://www.google.de/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"-->`), webbkoll still shows that link as a Third-party request.

### Expected behaviour
Webbkoll should not show commented images as a Third-party request.

**Comment by andersju** [comment]
I'm unable to reproduce this issue. Webbkoll itself doesn't inspect HTML at all (except for some meta elements), and third-party request info is based on actual network traffic reported by Chromium. Maybe the web server was still serving a cached version of the old page. Do you have a URL to a page that demonstrates this problem? (You can email me at anders@unix.se if you don't want to write it here.)

**Comment by NiklasDah** [comment]
Hey,

just re-checked. I found it, it was the same url - that's why I missed it, probably. After removing it, it works fine.

Sorry for wasting your time.
