### ISSUE TITLE
Issue while running the server

### ISSUE THREAD

**Issue by arunkp** [andersju/webbkoll#27]
Everything worked as expected but while running the server I encountered this issue. It would be much appreciated if anybody can help here:

![image](https://user-images.githubusercontent.com/4560500/96739400-0e548200-13c0-11eb-9c50-8d51d56e68f7.png)

**Comment by raphigithub** [comment]
I can confirm this issue, getting the same error code.

**Comment by andersju** [comment]
MaxMind (provider of the GeoIP database that Webbkoll tries to download) changed their policies at some point. If you look at `config/dev.exs` or `config/prod.exs `, you see, under `config :webbkoll`:
```
  geoip_db_url: "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz",
  geoip_db_md5_url: "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz.md5"
```
geolite.maxmind.com doesn't even resolve to anything anymore, hence the error. To get working URLs, you need to go to https://dev.maxmind.com/geoip/geoip2/geolite2/ and sign up for a (free) account and get a key. In the Webbkoll configuration it should then look like this (replacing YOUR_LICENSE_KEY_HERE with what you get from MaxMind):
```
  geoip_db_url: "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=YOUR_LICENSE_KEY_HERE&suffix=tar.gz",
  geoip_db_md5_url: "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=YOUR_LICENSE_KEY_HERE&suffix=tar.gz.md5"
```
