### ISSUE TITLE
Service unavailable, maximum number of allowed connections reached

### ISSUE THREAD

**Issue by superhuy** [andersju/webbkoll#3]
Sorry, but i'm still trying to set up webbkoll on my own server. 

Unfortunately i get this error:
(WorkerError) Service unavailable, maximum number of allowed connections reached.
Do you any idea?

And my second question is: How can i access the database.
I got the dump but i can't access with "SELECT * FROM database_name?".

Kind regards

**Comment by andersju** [comment]
>  (WorkerError) Service unavailable, maximum number of allowed connections reached.

That's an error from PhearJS meaning all its workers are currently in use. You can specify the number of workers in PhearJS' config file (`config/config.json`). Make sure that you have a matching number specified in Webbkoll's `config/dev.exs` in the queues setting. E.g. `queues: [{"q1", 5}],` if you have five workers.

> And my second question is: How can i access the database.
> I got the dump but i can't access with "SELECT * FROM database_name?".

It's a normal PostgreSQL database, so just access it with psql. E.g. `psql -U postgres webbkoll_dev`

**Comment by superhuy** [comment]
Hey,

unfortunately it doesn't work for me. I have configured the numbers and the number of workers but it hasn't changed anything. 
Is there a way to reboot phearjs and the web workers?

"my webbkoll" on my server works for several pages and then i get this error. Or is this error related to the database?

**Comment by andersju** [comment]
It must be something related to PhearJS, or more likely PhantomJS. How did you install PhearJS, and how are you starting it? What version of PhantomJS?
