### ISSUE TITLE
Problems starting the webbkoll frontend

### ISSUE THREAD

**Issue by chess-levin** [andersju/webbkoll#31]
Hello,

webbkol is a great tool for checking and training for good CSP-practice!

We like to run webbkoll backend and frontend. But we have no experience with erlang/elixir so far.

We are using hosts with centos 7.9. Webbkoll-Backend is already setup and running as a service.
But we get an error when trying the first step of the frontend setup tutorial:

```
 mix deps.get
** (UndefinedFunctionError) undefined function: Mix.compilers/0
    (mix) Mix.compilers()
    mix.exs:10: Webbkoll.Mixfile.project/0
    (mix) lib/mix/project.ex:348: Mix.Project.get_project_config/1
    (mix) lib/mix/project.ex:52: Mix.Project.push/2
    (stdlib) lists.erl:1248: :lists.foldl/3
```

We found there is a webbkoll-backend docker container (https://hub.docker.com/r/eeacms/webbkoll-backend), but we couldn't find a matching frontend container. Running webbkoll as containers would be the easiest solution for us. 

We hope you could help us, getting webkkol running.

Thank you in advance.

**Comment by andersju** [comment]
Hi!

If you're using Elixir installed from the normal CentOS repositories it's probably way too old (and the installed Erlang is then also too old). I'm not sure what the minimum version would be, but I use Elixir 1.12 and Erlang/OTP 24 here. (I know the Webbkoll README says "Erlang (>= 20) and Elixir (>= 1.7)", but that might no longer be true.)

The webbkoll-backend container was created by someone else, there are no "official" containers at the moment.

**Comment by chess-levin** [comment]
Hi @andersju 
I managed to start backend and frontend. But when I try to start an analysis via the frontend I always get this problem. I have no idea what to do about it. Could you help?


```
Compiling 27 files (.ex)
Generated webbkoll app
[warn] Job failed due to exception. %Honeydew.Job{by: :nonode@nohost, completed_at: nil, delay_secs: 0, enqueued_at: 1643292088978, failure_private: nil, from: nil, job_monitor: #PID<0.5634.0>, private: -576460752303321144, queue: Webbkoll.Queue.Q1, result: {:error, %Honeydew.Crash{reason: %RuntimeError{message: "econnrefused"}, stacktrace: [{Webbkoll.Worker, :handle_error, 2, [file: 'lib/webbkoll/worker.ex', line: 100]}, {Webbkoll.Worker, :perform, 4, [file: 'lib/webbkoll/worker.ex', line: 20]}, {Honeydew.JobRunner, :do_run, 1, [file: 'lib/honeydew/job_runner.ex', line: 58]}, {Honeydew.JobRunner, :handle_continue, 2, [file: 'lib/honeydew/job_runner.ex', line: 79]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 695]}, {:gen_server, :loop, 7, [file: 'gen_server.erl', line: 437]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}], type: :exception}}, started_at: nil, task: {:perform, ["999166dc-4845-407f-95ec-d83aecb395ea", "http://hmmh.de", nil, "http://localhost:8100/"]}}
** (RuntimeError) econnrefused
    (webbkoll 0.0.1) lib/webbkoll/worker.ex:100: Webbkoll.Worker.handle_error/2
    (webbkoll 0.0.1) lib/webbkoll/worker.ex:20: Webbkoll.Worker.perform/4
    (honeydew 1.5.0) lib/honeydew/job_runner.ex:58: Honeydew.JobRunner.do_run/1
    (honeydew 1.5.0) lib/honeydew/job_runner.ex:79: Honeydew.JobRunner.handle_continue/2
    (stdlib 3.16.1) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.16.1) gen_server.erl:437: :gen_server.loop/7
    (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3


[warn] Job failed due to exception. %Honeydew.Job{by: :nonode@nohost, completed_at: nil, delay_secs: 0, enqueued_at: 1643292088978, failure_private: 1, from: nil, job_monitor: #PID<0.5653.0>, private: -576460752303321144, queue: Webbkoll.Queue.Q1, result: {:error, %Honeydew.Crash{reason: %RuntimeError{message: "econnrefused"}, stacktrace: [{Webbkoll.Worker, :handle_error, 2, [file: 'lib/webbkoll/worker.ex', line: 100]}, {Webbkoll.Worker, :perform, 4, [file: 'lib/webbkoll/worker.ex', line: 20]}, {Honeydew.JobRunner, :do_run, 1, [file: 'lib/honeydew/job_runner.ex', line: 58]}, {Honeydew.JobRunner, :handle_continue, 2, [file: 'lib/honeydew/job_runner.ex', line: 79]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 695]}, {:gen_server, :loop, 7, [file: 'gen_server.erl', line: 437]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}], type: :exception}}, started_at: 1643292088978, task: {:perform, ["999166dc-4845-407f-95ec-d83aecb395ea", "http://hmmh.de", nil, "http://localhost:8100/"]}}
** (RuntimeError) econnrefused
    (webbkoll 0.0.1) lib/webbkoll/worker.ex:100: Webbkoll.Worker.handle_error/2
    (webbkoll 0.0.1) lib/webbkoll/worker.ex:20: Webbkoll.Worker.perform/4
    (honeydew 1.5.0) lib/honeydew/job_runner.ex:58: Honeydew.JobRunner.do_run/1
    (honeydew 1.5.0) lib/honeydew/job_runner.ex:79: Honeydew.JobRunner.handle_continue/2
    (stdlib 3.16.1) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.16.1) gen_server.erl:437: :gen_server.loop/7
    (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3


[warn] Job failed because {%RuntimeError{message: "econnrefused"}, [{Webbkoll.Worker, :handle_error, 2, [file: 'lib/webbkoll/worker.ex', line: 100]}, {Webbkoll.Worker, :perform, 4, [file: 'lib/webbkoll/worker.ex', line: 20]}, {Honeydew.JobRunner, :do_run, 1, [file: 'lib/honeydew/job_runner.ex', line: 58]}, {Honeydew.JobRunner, :handle_continue, 2, [file: 'lib/honeydew/job_runner.ex', line: 79]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 695]}, {:gen_server, :loop, 7, [file: 'gen_server.erl', line: 437]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}, abandoning: %Honeydew.Job{by: :nonode@nohost, completed_at: nil, delay_secs: 0, enqueued_at: 1643292088978, failure_private: nil, from: nil, job_monitor: #PID<0.5653.0>, private: -576460752303321144, queue: Webbkoll.Queue.Q1, result: {:retrying, {%RuntimeError{message: "econnrefused"}, [{Webbkoll.Worker, :handle_error, 2, [file: 'lib/webbkoll/worker.ex', line: 100]}, {Webbkoll.Worker, :perform, 4, [file: 'lib/webbkoll/worker.ex', line: 20]}, {Honeydew.JobRunner, :do_run, 1, [file: 'lib/honeydew/job_runner.ex', line: 58]}, {Honeydew.JobRunner, :handle_continue, 2, [file: 'lib/honeydew/job_runner.ex', line: 79]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 695]}, {:gen_server, :loop, 7, [file: 'gen_server.erl', line: 437]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}}, started_at: 1643292089147, task: {:perform, ["999166dc-4845-407f-95ec-d83aecb395ea", "http://hmmh.de", nil, "http://localhost:8100/"]}}
```

**Comment by andersju** [comment]
Looks like the kind of error you'd get if the "frontend" part can't access the backend (the backend being http://localhost:8100/).

If you run `curl http://localhost:8100/status` in a terminal (on the same server/computer where the frontend is running) it should respond "OK!". Does that happen?

**Comment by chess-levin** [comment]
@andersju Thank you for your feedback. I've run a curl to test if the backend is reachable and got an "OK!" in return. But still cannot run an analysis?

{code}
l# curl https://webbkoll.intern.hmmh.io/status
OK!root@f81082052103:/opt/webbkoll# mix phx.server
[warn] Job failed due to exception. %Honeydew.Job{by: :nonode@nohost, completed_at: nil, delay_secs: 0, enqueued_at: 1643362069354, failure_private: nil, from: nil, job_monitor: #PID<0.637.0>, private: -576460752303423294, queue: Webbkoll.Queue.Q1, result: {:error, %Honeydew.Crash{reason: %RuntimeError{message: "econnrefused"}, stacktrace: [{Webbkoll.Worker, :handle_error, 2, [file: 'lib/webbkoll/worker.ex', line: 100]}, {Webbkoll.Worker, :perform, 4, [file: 'lib/webbkoll/worker.ex', line: 20]}, {Honeydew.JobRunner, :do_run, 1, [file: 'lib/honeydew/job_runner.ex', line: 58]}, {Honeydew.JobRunner, :handle_continue, 2, [file: 'lib/honeydew/job_runner.ex', line: 79]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 695]}, {:gen_server, :loop, 7, [file: 'gen_server.erl', line: 437]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}], type: :exception}}, started_at: nil, task: {:perform, ["a8797661-c824-4f4f-affc-ebe84c22fb44", "http://hmmh.de", nil, "http://localhost:8100/"]}}
** (RuntimeError) econnrefused
    (webbkoll 0.0.1) lib/webbkoll/worker.ex:100: Webbkoll.Worker.handle_error/2
    (webbkoll 0.0.1) lib/webbkoll/worker.ex:20: Webbkoll.Worker.perform/4
    (honeydew 1.5.0) lib/honeydew/job_runner.ex:58: Honeydew.JobRunner.do_run/1
    (honeydew 1.5.0) lib/honeydew/job_runner.ex:79: Honeydew.JobRunner.handle_continue/2
    (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17) gen_server.erl:437: :gen_server.loop/7
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3


[warn] Job failed due to exception. %Honeydew.Job{by: :nonode@nohost, completed_at: nil, delay_secs: 0, enqueued_at: 1643362069354, failure_private: 1, from: nil, job_monitor: #PID<0.659.0>, private: -576460752303423294, queue: Webbkoll.Queue.Q1, result: {:error, %Honeydew.Crash{reason: %RuntimeError{message: "econnrefused"}, stacktrace: [{Webbkoll.Worker, :handle_error, 2, [file: 'lib/webbkoll/worker.ex', line: 100]}, {Webbkoll.Worker, :perform, 4, [file: 'lib/webbkoll/worker.ex', line: 20]}, {Honeydew.JobRunner, :do_run, 1, [file: 'lib/honeydew/job_runner.ex', line: 58]}, {Honeydew.JobRunner, :handle_continue, 2, [file: 'lib/honeydew/job_runner.ex', line: 79]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 695]}, {:gen_server, :loop, 7, [file: 'gen_server.erl', line: 437]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}], type: :exception}}, started_at: 1643362069355, task: {:perform, ["a8797661-c824-4f4f-affc-ebe84c22fb44", "http://hmmh.de", nil, "http://localhost:8100/"]}}
** (RuntimeError) econnrefused
    (webbkoll 0.0.1) lib/webbkoll/worker.ex:100: Webbkoll.Worker.handle_error/2
    (webbkoll 0.0.1) lib/webbkoll/worker.ex:20: Webbkoll.Worker.perform/4
    (honeydew 1.5.0) lib/honeydew/job_runner.ex:58: Honeydew.JobRunner.do_run/1
    (honeydew 1.5.0) lib/honeydew/job_runner.ex:79: Honeydew.JobRunner.handle_continue/2
    (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17) gen_server.erl:437: :gen_server.loop/7
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3


[warn] Job failed because {%RuntimeError{message: "econnrefused"}, [{Webbkoll.Worker, :handle_error, 2, [file: 'lib/webbkoll/worker.ex', line: 100]}, {Webbkoll.Worker, :perform, 4, [file: 'lib/webbkoll/worker.ex', line: 20]}, {Honeydew.JobRunner, :do_run, 1, [file: 'lib/honeydew/job_runner.ex', line: 58]}, {Honeydew.JobRunner, :handle_continue, 2, [file: 'lib/honeydew/job_runner.ex', line: 79]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 695]}, {:gen_server, :loop, 7, [file: 'gen_server.erl', line: 437]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}, abandoning: %Honeydew.Job{by: :nonode@nohost, completed_at: nil, delay_secs: 0, enqueued_at: 1643362069354, failure_private: nil, from: nil, job_monitor: #PID<0.659.0>, private: -576460752303423294, queue: Webbkoll.Queue.Q1, result: {:retrying, {%RuntimeError{message: "econnrefused"}, [{Webbkoll.Worker, :handle_error, 2, [file: 'lib/webbkoll/worker.ex', line: 100]}, {Webbkoll.Worker, :perform, 4, [file: 'lib/webbkoll/worker.ex', line: 20]}, {Honeydew.JobRunner, :do_run, 1, [file: 'lib/honeydew/job_runner.ex', line: 58]}, {Honeydew.JobRunner, :handle_continue, 2, [file: 'lib/honeydew/job_runner.ex', line: 79]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 695]}, {:gen_server, :loop, 7, [file: 'gen_server.erl', line: 437]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}}, started_at: 1643362069621, task: {:perform, ["a8797661-c824-4f4f-affc-ebe84c22fb44", "http://hmmh.de", nil, "http://localhost:8100/"]}}
{code}

**Comment by andersju** [comment]
You're curling `https://webbkoll.intern.hmmh.io/`, but the Webbkoll app is trying to use `http://localhost:8100/`. Edit `config/dev.exs` or `config/prod.exs` and change `http://localhost:8100/` to `https://webbkoll.intern.hmmh.io/` in the section about backends.

**Comment by chess-levin** [comment]
> You're curling `https://webbkoll.intern.hmmh.io/`, but the Webbkoll app is trying to use `http://localhost:8100/`. Edit `config/dev.exs` or `config/prod.exs` and change `http://localhost:8100/` to `https://webbkoll.intern.hmmh.io/` in the section about backends.

Oh yes. Sorry, I forgot to change it. I installed the frontend in a docker container.

Now everything seems up & running, but I always get 'timeout' errors like this

<img width="979" alt="image" src="https://user-images.githubusercontent.com/6573503/151986143-1f6b0ed7-8b63-4637-bdf7-7fdb3d240a85.png">

```[warn] Job failed due to exception. %Honeydew.Job{by: :nonode@nohost, completed_at: nil, delay_secs: 0, enqueued_at: 1643725068573, failure_private: 1, from: nil, job_monitor: #PID<0.1454.0>, private: -576460752303422843, queue: Webbkoll.Queue.Q1, result: {:error, %Honeydew.Crash{reason: %RuntimeError{message: "timeout"}, stacktrace: [{Webbkoll.Worker, :handle_error, 2, [file: 'lib/webbkoll/worker.ex', line: 100]}, {Webbkoll.Worker, :perform, 4, [file: 'lib/webbkoll/worker.ex', line: 20]}, {Honeydew.JobRunner, :do_run, 1, [file: 'lib/honeydew/job_runner.ex', line: 58]}, {Honeydew.JobRunner, :handle_continue, 2, [file: 'lib/honeydew/job_runner.ex', line: 79]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 695]}, {:gen_server, :loop, 7, [file: 'gen_server.erl', line: 437]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}], type: :exception}}, started_at: 1643725068573, task: {:perform, ["2ffb8a47-794d-428b-9c27-54b7b74c52fe", "http://cspdemo.intern.hmmh.io:443/csp_demo/start", nil, "http://webbkoll.intern.hmmh.io:8100/"]}}
** (RuntimeError) timeout
    (webbkoll 0.0.1) lib/webbkoll/worker.ex:100: Webbkoll.Worker.handle_error/2
    (webbkoll 0.0.1) lib/webbkoll/worker.ex:20: Webbkoll.Worker.perform/4
    (honeydew 1.5.0) lib/honeydew/job_runner.ex:58: Honeydew.JobRunner.do_run/1
    (honeydew 1.5.0) lib/honeydew/job_runner.ex:79: Honeydew.JobRunner.handle_continue/2
    (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17) gen_server.erl:437: :gen_server.loop/7
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3


[warn] Job failed because {%RuntimeError{message: "timeout"}, [{Webbkoll.Worker, :handle_error, 2, [file: 'lib/webbkoll/worker.ex', line: 100]}, {Webbkoll.Worker, :perform, 4, [file: 'lib/webbkoll/worker.ex', line: 20]}, {Honeydew.JobRunner, :do_run, 1, [file: 'lib/honeydew/job_runner.ex', line: 58]}, {Honeydew.JobRunner, :handle_continue, 2, [file: 'lib/honeydew/job_runner.ex', line: 79]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 695]}, {:gen_server, :loop, 7, [file: 'gen_server.erl', line: 437]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}, abandoning: %Honeydew.Job{by: :nonode@nohost, completed_at: nil, delay_secs: 0, enqueued_at: 1643725068573, failure_private: nil, from: nil, job_monitor: #PID<0.1454.0>, private: -576460752303422843, queue: Webbkoll.Queue.Q1, result: {:retrying, {%RuntimeError{message: "timeout"}, [{Webbkoll.Worker, :handle_error, 2, [file: 'lib/webbkoll/worker.ex', line: 100]}, {Webbkoll.Worker, :perform, 4, [file: 'lib/webbkoll/worker.ex', line: 20]}, {Honeydew.JobRunner, :do_run, 1, [file: 'lib/honeydew/job_runner.ex', line: 58]}, {Honeydew.JobRunner, :handle_continue, 2, [file: 'lib/honeydew/job_runner.ex', line: 79]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 695]}, {:gen_server, :loop, 7, [file: 'gen_server.erl', line: 437]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}}, started_at: 1643725213603, task: {:perform, ["2ffb8a47-794d-428b-9c27-54b7b74c52fe", "http://cspdemo.intern.hmmh.io:443/csp_demo/start", nil, "http://webbkoll.intern.hmmh.io:8100/"]}}
```

**Comment by chess-levin** [comment]
> You're curling `https://xxx.yyy.zzz/`, but the Webbkoll app is trying to use `http://localhost:8100/`. Edit `config/dev.exs` or `config/prod.exs` and change `http://localhost:8100/` to `https://xxx.yyy.zzz/` in the section about backends.

Sorry, andersju. In my last question I disclosed an internal address. Would you be so kind to delete your answer or rewrite it with xxx. Thank you.

I found out, that out that our CentOs Kernel is to old and Puppeteer/Chrome is not working correctly. So I have reinstall the backend on a recent Ubuntu.

**Comment by andersju** [comment]
> > You're curling `https://xxx.yyy.zzz/`, but the Webbkoll app is trying to use `http://localhost:8100/`. Edit `config/dev.exs` or `config/prod.exs` and change `http://localhost:8100/` to `https://xxx.yyy.zzz/` in the section about backends.
> 
> Sorry, andersju. In my last question I disclosed an internal address. Would you be so kind to delete your answer or rewrite it with xxx. Thank you.

Sure. The history of edited comments is still accessible so I deleted it :)
