### ISSUE TITLE
More alternative tests

### ISSUE THREAD

**Issue by Seirdy** [andersju/webbkoll#38]
Some more tests to include in [the "about" page's alternatives section](https://webbkoll.dataskydd.net/en/about#alternatives):

- [Check Your Website](https://check-your-website.server-daten.de/): one of the most in-depth tests out there. It seems to include much of (but not all of) Webbkoll's functionality, and all of Hardenize's functionality. Appears to use a real browser for some of its tests.

- [Internet.nl](https://internet.nl): in my experience, this is one of the harshest web security tests. It tests some security headers, TLS (ciphers, key exchange params, hash function, etc), DNSSEC, RPKI, and IPv6.

Check Your Website, Internet.nl, and Webbkoll make most other web security checks redundant, IME.

**Comment by andersju** [comment]
Thanks! I've added them; they'll be visible once I've updated the server, sometime soon.
