### ISSUE TITLE
Content-Security-Policy in html meta not detected?

### ISSUE THREAD

**Issue by peterk** [andersju/webbkoll#5]
It is possible to set CSP in a html meta element but webbkoll does not seem to detect it. See e.g. view-source:https://kortkataloger.kb.se/ but where the test result warns about missing CSP.

**Comment by andersju** [comment]
Yep, good catch. I think I'll refactor it a bit to show CSP separately from the headers. Should be fixed soon. Nice work with the site!

**Comment by peterk** [comment]
Great! Thx for feedback.

**Comment by andersju** [comment]
Fixed, and https://webbkoll.dataskydd.net/ is now running the new version. Thanks for reporting!
