### ISSUE TITLE
Check not possible when behind Nginx?

### ISSUE THREAD

**Issue by ridoo** [andersju/webbkoll#7]
The tool fails checking a Website when sending invalid data chunks. Nginx logs the following:

```
51.15.235.198 - - [23/May/2018:10:11:57 +0000] "-" 400 0 "-" "-"
51.15.235.198 - - [23/May/2018:10:11:57 +0000] "-" 400 0 "-" "-"
51.15.235.198 - - [23/May/2018:10:11:57 +0000] "-" 400 0 "-" "-"
```

After 3 or 5 seconds the Tool says 

```
Error: Failed to fetch this URL.

Try again?
```

**Comment by andersju** [comment]
Can you provide the URL of a website where this happens, so I can test? (You can email anders@unix.se if you don't want to do it here)

**Comment by andersju** [comment]
We've now switched from PhantomJS (which had all kinds of issues) to Puppeteer (running a recent version of Chromium), which appears to have fixed this issue.
