### ISSUE TITLE
deployed on amazon vps its giving errconnectionrefused.

### ISSUE THREAD

**Issue by ashishcompwiz** [andersju/webbkoll#9]
deployed on amazon vps its giving errconnectionrefused.
http://18.218.57.138:4000

all out going teaffic is allowed on all ports. in amazon aws and also in ufw

here is sudo ufw status

Status: active

To                         Action      From
--                         ------      ----
22                         ALLOW       Anywhere
80                         ALLOW       Anywhere
443                        ALLOW       Anywhere
4000                       ALLOW       Anywhere
22 (v6)                    ALLOW       Anywhere (v6)
80 (v6)                    ALLOW       Anywhere (v6)
443 (v6)                   ALLOW       Anywhere (v6)
4000 (v6)                  ALLOW       Anywhere (v6)

Also here is error screenshot
![image](https://user-images.githubusercontent.com/32674479/43200109-ed09aad0-9031-11e8-8d0a-335c7a3954f4.png)

what could be the issue?

**Comment by andersju** [comment]
Apologies for the late reply (holidays, etc).

Looks like the backend isn't running. See https://github.com/andersju/webbkoll#backend
